joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
    joint_6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_body__left_ext

# gripper_controller:
#   type: effort_controllers/JointPositionController
#   joint: gripper_body__left_ext
#   # pid: {p: 1.5, i: 0.0005, d: 0.5, i_min: -1, i_max: 1}
#   pid: {p: 5.0, i: 2.0, d: 0.01, i_clamp_min: -1, i_clamp_max: 1}

# gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - gripper_body__left_ext
#   constraints:
#     goal_time: 0.6
#     stopped_velocity_tolerance: 0.05
#     gripper_body__left_ext: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10


