controller_list:
  - name: fake_irb140_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    joints:
      - gripper_body__left_ext
      - gripper_body__right_ext